# 🥷 Vagabond Theme – Inspired by Takehiko Inoue's masterpiece

$GTK_THEME = Adwaita-dark
$ICON_THEME = Tela-circle-dark
$COLOR_SCHEME = prefer-dark

exec = gsettings set org.gnome.desktop.interface icon-theme $ICON_THEME
exec = gsettings set org.gnome.desktop.interface gtk-theme $GTK_THEME
exec = gsettings set org.gnome.desktop.interface color-scheme $COLOR_SCHEME

general {
    gaps_in = 2
    gaps_out = 6
    border_size = 2
    col.active_border = rgba(8b0000ff) rgba(ffffff88) 45deg        # deep red to parchment
    col.inactive_border = rgba(2e2e2ecc) rgba(000000cc) 45deg       # grey-black gradient
    layout = dwindle
    resize_on_border = true
}

group {
    col.border_active = rgba(8b0000ff) rgba(ffffff88) 45deg
    col.border_inactive = rgba(2e2e2ecc) rgba(000000cc) 45deg
    col.border_locked_active = rgba(8b0000ff) rgba(ffffff88) 45deg
    col.border_locked_inactive = rgba(2e2e2ecc) rgba(000000cc) 45deg
}

decoration {
    rounding = 6
    shadow:enabled = false

    blur {
        enabled = yes
        size = 5
        passes = 2
        new_optimizations = on
        ignore_opacity = on
        xray = false
    }
}

layerrule = blur,waybar
