foreground #fceaff
background #1a1a1f
selection_foreground #1a1a1f
selection_background #f7c1e0
cursor #ffc9ec
cursor_text_color #1a1a1f

color0  #2e2e3a
color8  #472d3c

color1  #c14a7d
color9  #ff85b3

color2  #a18bb9
color10 #d1addd

color3  #f7c1e0
color11 #ffb3d9

color4  #809fb3
color12 #c0e0e8

color5  #ff85b3
color13 #ffc9ec

color6  #809fb3
color14 #c0e0e8

color7  #fceaff
color15 #ffffff

